[package]
name = "starroom-portrait"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
ort = { version = "=2.0.0-rc.10", features = ["directml"] }
ndarray = "0.16"
starroom-detail = { path = "../starroom-detail" }
starroom-color = { path = "../starroom-color" }
